apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: board
          image: 598552988151.dkr.ecr.ap-northeast-2.amazonaws.com/board:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: board
spec:
  selector:
    app: board
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer